### ISSUE TITLE
运行python servers.py提示下面这个怎么办？

### ISSUE THREAD

**Issue by hrkkid** [fsgmhoward/shadowsocks-py-mu#44]
root@root:~/shadowsocks-py-mu/shadowsocks# python servers.py
Traceback (most recent call last):
  File "servers.py", line 55, in <module>
    import manager
  File "/root/shadowsocks-py-mu/shadowsocks/manager.py", line 26, in <module>
    import json
ImportError: No module named json

**Comment by fsgmhoward** [comment]
你的Python版本过旧，json轮子在python 2.6+就内置了。
如果你的python版本>=2.5，请尝试执行`pip install simplejson`后再运行SS。
如果你的python版本比2.5还要老的话，请尝试安装高版本python。
