### ISSUE TITLE
ERROR Except thrown while pushing user data

### ISSUE THREAD

**Issue by ki1lermaster** [fsgmhoward/shadowsocks-py-mu#53]
Hi Both ,

Have you ever encountered a similar issue ?

Sep 25 21:56:53 ERROR Except thrown while pushing user data:[Errno socket error] timed out

thanks !

**Comment by fsgmhoward** [comment]
No. I have never experienced such problem before and no similar issue has been opened. If the situation persists, please post your log with `SS_VERBOSE` set to `True` and `LOG_LEVEL` set to `logging.DEBUG` in the configuration file.

Btw, please delete any sensitive info before posting such as email addresses.

**Comment by ki1lermaster** [comment]
Hi Howard , 

about  the SS_LOG as below .  

"config.py" [converted] 101L, 3417C written                                                                                                                    
killermaster@killermaster:~/ss-panel/shadowsocks-py-mu/shadowsocks$ python servers.py 
Oct 08 19:59:43 INFO -----------------------------------------
Oct 08 19:59:43 INFO Multi-User Shadowsocks Server Starting...
Oct 08 19:59:43 INFO Current Server Version: 3.4.0

Oct 08 19:59:43 INFO Now using MultiUser API as the user interface
Oct 08 19:59:43 INFO Now starting manager thread...
Oct 08 19:59:48 INFO Now starting user pulling thread...
Oct 08 19:59:53 INFO Now starting user pushing thread...
Oct 08 19:59:53 INFO api upload: pushing transfer statistics
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 288, in pull_api_user
    f = urllib.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] timed out
Oct 08 20:00:18 ERROR Except thrown while pulling user data:[Errno socket error] timed out
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 243, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 84, in push_db_all_user
    users = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 288, in pull_api_user
    f = urllib.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] timed out
Oct 08 20:00:23 ERROR Except thrown while pushing user data:[Errno socket error] timed out
^CTraceback (most recent call last):
  File "servers.py", line 120, in <module>
    main()
  File "servers.py", line 116, in main
    time.sleep(100)
KeyboardInterrupt
killermaster@killermaster:~/ss-panel/shadowsocks-py-mu/shadowsocks$

**Comment by fsgmhoward** [comment]
Error 500 is HTTP **Internal Server Error** and timeout shows that your shadowsocks server has no way to fetch information from your panel because it takes too long to respond. Please check the configuration of your web server which is hosting your ss-panel or whatever you are using. **This is not an issue caused by shadowsocks server**. If necessary, please open an issue at the repository of the panel you are using.

**Comment by ki1lermaster** [comment]
as blow is SS DEBUG  log 👍 



killermaster@killermaster:~/ss-panel/shadowsocks-py-mu/shadowsocks$ python servers.py 
Oct 08 20:43:06 INFO -----------------------------------------
Oct 08 20:43:06 INFO Multi-User Shadowsocks Server Starting...
Oct 08 20:43:06 INFO Current Server Version: 3.4.0

Oct 08 20:43:06 INFO Now using MultiUser API as the user interface
Oct 08 20:43:06 INFO Now starting manager thread...
Oct 08 20:43:06 DEBUG using event model: epoll
Oct 08 20:43:11 INFO Now starting user pulling thread...
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 289, in pull_api_user
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Oct 08 20:43:12 ERROR Except thrown while pulling user data:No JSON object could be decoded
Oct 08 20:43:16 INFO Now starting user pushing thread...
Oct 08 20:43:16 INFO api upload: pushing transfer statistics
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 243, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 84, in push_db_all_user
    users = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 289, in pull_api_user
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Oct 08 20:43:16 ERROR Except thrown while pushing user data:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 289, in pull_api_user
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Oct 08 20:43:42 ERROR Except thrown while pulling user data:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 289, in pull_api_user
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Oct 08 20:44:12 ERROR Except thrown while pulling user data:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/home/killermaster/ss-panel/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 289, in pull_api_user
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Oct 08 20:44:42 ERROR Except thrown while pulling user data:No JSON object could be decoded
^CTraceback (most recent call last):
  File "servers.py", line 120, in <module>
    main()
  File "servers.py", line 116, in main
    time.sleep(100)
KeyboardInterrupt
killermaster@killermaster:~/ss-panel/shadowsocks-py-mu/shadowsocks$

**Comment by fsgmhoward** [comment]
@ki1lermaster Same as above,   there are issues with the configuration of your **web server**, or you may have input a wrong API url in shadowsocks-py-mu's configuration file. Please contact **maintainers of your web panel instead of maintainers of this project** for help.

**Comment by ki1lermaster** [comment]
@fsgmhoward
 okay ,I will try to double check the API value  , Can you make it clear that I need to check those places?

**Comment by ki1lermaster** [comment]
@fsgmhoward
as my checked ,From the beginning to the end, I only modified the API value of CONFIG. PY .

anyway ,i attached related files as below 

####################################################
sudo vim /etc/nginx/sites-enabled/ss-panel
server {
    listen 80;

   server_name 192.168.1.244;

    root /home/alber/ss-panel/public/;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

####################################################################


**killermaster@killermaster:~/ss-panel$ vim .env**

/  ss-panel v3 配置
/
// !!! 修改此key为随机字符串确保网站安全 !!!
key = 'randomKey'
env = 'prod'  // 正式环境请保持env为prod确保安全
debug =  'false'  //  正式环境请确保为false
appName = 'ss-panel3'             //站点名称
baseUrl = 'http://192.168.1.244'            // 站点地址
timeZone = 'PRC'        // RPC 天朝时间  UTC 格林时间
pwdMethod = 'md5'       // 密码加密   可选 md5,sha256
salt = ''               // 密码加密用，从旧版升级请留空
theme    = 'default'   // 主题
session = 'file'
cache   = 'file'
tokenDriver = 'db'
// mu key 用于校验ss-go mu的请求
muKey = 'test'
// 邮件
mailDriver = 'mailgun'   // mailgun   #smtp不在支持,仅供测试


# database 数据库配置
db_driver = 'mysql'
db_host = 'localhost'
db_port = '3306'
db_database = 'shadowsocks'
db_username = 'root'
db_password = 12345678'
db_charset = 'utf8'
db_collation = 'utf8_general_ci'
db_prefix = ''

###
killermaster@killermaster:~/ss-panel/shadowsocks-py-mu/shadowsocks$ vim config.py
# Database Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = '12345678'
MYSQL_DB = 'shadowsocks'
# USUALLY this variable do not need to be changed
MYSQL_USER_TABLE = 'user'
# This is also the timeout of connecting to the API
MYSQL_TIMEOUT = 30

# Shadowsocks MultiUser API Settings
API_URL = 'http://192.168.199.244/mu'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = '**test**'
NODE_ID = '1'
